### ISSUE TITLE
Alternative to did.json to facilitate multi-tenant usage

### ISSUE THREAD

**Issue by sembrat** [digitalcredentials/cred-admin#4] opened 2023-04-05 13:29 UTC
Current utilization of did.json requires a file sit in the webroot of a publicly accessible URL. We have a client where their web hosting lacks a persistent contact and may be unreliable over a longer period of time, so it would be helpful to have an alternative DID authorization that is stored elsewhere (centrally?).

**Comment by stuartf** [comment] 2023-04-10 12:53
This is really a duplicate of #3

**Closed by stuartf** 2023-04-10 12:53 UTC
